export const ROUTES = {
  Splash: 'Splash',
  Auth: 'Auth',
  Main: 'Main',
  MyVehiclesTab: 'MyVehiclesTab',

  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Onboarding: 'Onboarding',
  AccountType: 'AccountType',
  OTPVerification: 'OTPVerification',
  CompleteProfile: 'CompleteProfile',
  ForgotPassword: 'ForgotPassword',
  CreatePassword: 'CreatePassword',
  MyVehicles: 'MyVehicles',

  Explore: 'Explore',
  MyRequests: 'MyRequests',
  SettingsTab: 'SettingsTab',
  ChatTab: 'ChatTab',
  FavoriteTab: 'FavoriteTab',
  BookingTab: 'BookingTab',
  ExploreTab: 'ExploreTab',
  CarFilter: 'CarFilter',
  CarDetail: 'CarDetail',
  PickupAndReturnInfo: 'PickupAndReturnInfo',
  Checkout: 'Checkout',
  DriverInfo: 'ApprovedToDrive',
  RentalTermsAndConditions: 'RentalTermsAndConditions',
  DriverPhoto: 'DriverPhoto',
  DriverPhoneNumber: 'DriverPhoneNumber',
  DriverLicense: 'DriverLicense',
  LocationBasedSearch: 'LocationBasedSearch',
  SelectLocationOnMap: 'SelectLocationOnMap',
  SearchedPosts: 'SearchedPosts',
  DeleteAccount: 'DeleteAccount',
  Wallet: 'Wallet',
  WithdrawInfo: 'WithdrawInfo',
  TransactionHistory: 'TransactionHistory',

  Bookings: 'Bookings',
  AddReview: 'AddReview',
  TermsAndConditions: 'TermsAndConditions',
  PrivacyPolicy: 'PrivacyPolicy',

  FavoritePosts: 'FavoritePosts',
  ChatRoom: 'ChatRoom',
  ChatHeads: 'ChatHeads',
  Settings: 'Settings',
  ChangePassword: 'ChangePassword',
  AboutUs: 'AboutUs',
  ContactUs: 'ContactUs',
  MyReviews: 'MyReviews',
  RequestsTab: 'RequestsTab',
  AddVehicle: 'AddVehicle',
  AddRentalTermsAndConditions: 'AddRentalTermsAndConditions',
};
